name: Set Issue Status on Project Board
description: Moves an issue or pull request into a specific status column on a project board, adding the issue to the board if necessary. This action uses the new ProjectV2 API.
inputs:
  project-url:
    required: true
    description: URL of the project to add issues to
  github-token:
    description: Personal Access Token with projects scope
    required: true
  new-status:
    description: New status, e.g. "In Development"
    required: true
  add-to-top-of-column:
    description: Moves the card for this issue to the top of this column
    required: true
    default: "false"
  replace:
    description: Try to delete any existing card for the issue/PR before creating a new one
    required: false
    default: "false"
  issue-node-id:
    description: Issue Node ID (optional, by default taken from context)
    required: false
outputs:
  card-node-id: # id of output
    description: Node ID of the card created or updated
runs:
  using: 'node16'
  main: 'index.js'
