name: Add issues and PRs to project board
on:
  issues:
    types:
      - opened
      - closed
  pull_request:
    types:
      - opened
      - review_requested
      - ready_for_review

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/flexponsive/projects/3
          github-token: ${{ secrets.PROJECT_TOKEN }}
          new-status: "In Progress"
          add-to-top-of-column: true
